### ISSUE TITLE
Build problem Java10 not detected

### ISSUE THREAD

**Issue by zxsampo** [thefinn93/signald#6]
git clone https://git.callpipe.com/finn/signald
cd signald
make installDist

"./gradlew" installDist

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.

java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

Which java version is required? Was this somewhere documented and I
just missed it?

Cheers,
--Sampo

**Comment by thefinn93** [comment]
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

on my machine. I'm not really sure what is required, just what's worked for me so far. I suspect a few changes to `build.gradle` could make it work on your java 10.0.2, but i could be wrong.

**Comment by demure** [comment]
There seems to be a similar issue with debian's `openjdk-11-jre-headless` and `openjdk-12-jre-headless` packages:

```
-> make installDist                                                                                                                                                                                                                                             
"./gradlew" installDist                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                 
FAILURE: Build failed with an exception.                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                 
* What went wrong:                                                                                                                                                                                                                                                               
Could not determine java version from '11.0.3'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
make: *** [Makefile:20: installDist] Error 1
```
and
```
-> make installDist                                                                                                                                                                                                                                             
"./gradlew" installDist                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                 
FAILURE: Build failed with an exception.                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                 
* What went wrong:                                                                                                                                                                                                                                                               
Could not determine java version from '12'.                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                 
* Try:                                                                                                                                                                                                                                                                           
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.                                                                                                                                                                   
make: *** [Makefile:20: installDist] Error 1
```

**Comment by thefinn93** [comment]
Okay, so it [seems like this is a gradle thing](https://github.com/gradle/gradle/issues/4515) and [a fix was merged](https://github.com/gradle/gradle/pull/4759) for at least Java 11. I didn't find one for Java 12, but I upgraded the gradle wrapper and pushed it into a branch called `upgrade-gradlew`, could you both try that branch and see if it builds?

**Comment by demure** [comment]
looks like `make installDist` is now good for 11. Not sure on 12. It got further, but my server also happened to crash during the v12 make.

**Comment by zxsampo** [comment]
I did git pull on https://git.callpipe.com/finn/signald and tried make installDist. The problem remains.

I am not a Java developer nor have any interest in becoming one. Is gradle (why is it even needed?)
part of the signald git repo or am I somehow supposed to have installed it on my machine?

which gradle does not see any gradle. If this is an external dependency, how am I supposed
to install it? Any apt install command line I should use? README should explain this.

--Sampo

**Comment by thefinn93** [comment]
>I did git pull on https://git.callpipe.com/finn/signald and tried make installDist. The problem remains.

Did you check out the `update-gradlew` branch? If not, could you please run `git checkout update-gradlew` in the repo and try running `make installDist` again?

>I am not a Java developer nor have any interest in becoming one.

I'm not a "java developer" either, this is my first big project in Java, and the goal of it is to let people interact with Signal without them having to be a java developer.

> Is gradle (why is it even needed?) part of the signald git repo or am I somehow supposed to have installed it on my machine?

[Gradle](https://gradle.org/) is a build tool that does things like dependency management, kind of like npm/yarn, pip, etc. but also other build tasks.

Unlike npm/yarn/pip, Gradle also has [The Gradle Warpper](https://docs.gradle.org/current/userguide/gradle_wrapper.html), a short script which downloads and executes a specific version of gradle for those that don't have gradle installed. In that `update-gradlew` branch, I have updated the version of the gradle wrapper.

>which gradle does not see any gradle. If this is an external dependency, how am I supposed
to install it? Any apt install command line I should use?

You can also install a specific version of gradle from apt. The `Makefile` will only use gradlew [if gradle isn't installed on the system](https://github.com/thefinn93/signald/blob/master/Makefile#L9-L11).

> README should explain this.

I'm on the fence about this. Language-specific build tools are pretty common, explaining how to use them (beyond exactly which command to run to make the project build and run) aren't typically included in READMEs, and gradle isn't exactly an unusual tool. To the best of my knowledge, there hasn't really been an issue with gradle (short of this one, which it's unlikely that any README explanation of gradle would cover), so I probably won't add more to the already long README right now.

**Comment by thefinn93** [comment]
I have merged the changes into master, please re-open if this is not resolved.
